/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3ea1cef0f9bcb7c64058334db22a00ce)
interface __BaseEnv_Env {
	ANALYTICS: AnalyticsEngineDataset;
	CONTACT_LIMITER: RateLimit;
	CONTACT_GLOBAL_LIMITER: RateLimit;
	EVENT_LIMITER: RateLimit;
	ASSETS: Fetcher;
	CONTACT_EMAIL: "webzalokal@gmail.com";
	CONTACT_FROM: "WebZaLokal <onboarding@resend.dev>";
	APP_VERSION: "2026.08.26-1";
	RESEND_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONTACT_EMAIL" | "CONTACT_FROM" | "APP_VERSION" | "RESEND_API_KEY">> {}
}
