/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 58f86c755504eab5bc8d245e2ca722f8)
interface __BaseEnv_Env {
	LEADS_DB: D1Database;
	ANALYTICS: AnalyticsEngineDataset;
	CONTACT_LIMITER: RateLimit;
	CONTACT_GLOBAL_LIMITER: RateLimit;
	EVENT_LIMITER: RateLimit;
	LEAD_SEARCH_LIMITER: RateLimit;
	ASSETS: Fetcher;
	CONTACT_EMAIL: "webzalokal@gmail.com";
	CONTACT_FROM: "WebZaLokal <onboarding@resend.dev>";
	APP_VERSION: "2026.09.01-4";
	LEAD_FINDER_USERNAME: "webzalokal";
	LEAD_SEARCH_MONTHLY_REQUEST_LIMIT: "100";
	RESEND_API_KEY: string;
	GOOGLE_PLACES_API_KEY: string;
	LEAD_FINDER_ACCESS_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONTACT_EMAIL" | "CONTACT_FROM" | "APP_VERSION" | "LEAD_FINDER_USERNAME" | "LEAD_SEARCH_MONTHLY_REQUEST_LIMIT" | "RESEND_API_KEY" | "GOOGLE_PLACES_API_KEY" | "LEAD_FINDER_ACCESS_TOKEN">> {}
}
